### ISSUE TITLE
[1.0.2/3]Mixin apply failed

### ISSUE THREAD

**Issue by Yoghurt4C** [CottonMC/SkillCheck#13]
```[21:36:39] [main/FATAL]: Mixin apply failed skillcheck.common.json:MixinThiefCommon -> net.minecraft.class_1657: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Resolution error: unable to find corresponding type for io/github/cottonmc/skillcheck/mixins/ArrowEffects in hierarchy of net/minecraft/class_1657
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Resolution error: unable to find corresponding type for io/github/cottonmc/skillcheck/mixins/ArrowEffects in hierarchy of net/minecraft/class_1657
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.findRealType(MixinTargetContext.java:438) ~[sponge-mixin-0.7.11.30.jar:0.7.11.30+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:913) ~[sponge-mixin-0.7.11.30.jar:0.7.11.30+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:865) ~[sponge-mixin-0.7.11.30.jar:0.7.11.30+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformTypeNode(MixinTargetContext.java:654) ~[sponge-mixin-0.7.11.30.jar:0.7.11.30+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:471) ~[sponge-mixin-0.7.11.30.jar:0.7.11.30+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:446) ~[sponge-mixin-0.7.11.30.jar:0.7.11.30+unknown-b0.git-unknown]```

**Comment by LemmaEOF** [comment]
Did you check that this is happening in 1.0.3? Kitten just changed this mixin so it mighta made stuff work better.

**Comment by Yoghurt4C** [comment]
![image](https://user-images.githubusercontent.com/11313954/57478299-3bcc6f00-72a3-11e9-9124-78dd1650fb24.png)
🦀
