### ISSUE TITLE
I can't seem to get the game to load with this mod

### ISSUE THREAD

**Issue by werff** [CottonMC/SkillCheck#17]
I put this in here.

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 16/05/19 17:16
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoSuchMethodError: net.fabricmc.fabric.impl.tools.ToolManager.entry(Lnet/minecraft/class_2248$class_2251;)Lnet/fabricmc/fabric/impl/tools/ToolManager$Entry;
		at net.fabricmc.fabric.api.block.FabricBlockSettings.breakByTool(FabricBlockSettings.java:98)
		at net.fabricmc.fabric.api.block.FabricBlockSettings.breakByTool(FabricBlockSettings.java:94)
		at io.github.cottonmc.epicurean.block.CookingTableBlock.<init>(CookingTableBlock.java:21)
		at io.github.cottonmc.epicurean.block.EpicureanBlocks.<clinit>(EpicureanBlocks.java:15)
		at io.github.cottonmc.epicurean.EpicureanGastronomy.onInitialize(EpicureanGastronomy.java:41)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointClient$$Lambda$1431/532907768.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils$$Lambda$1432/2058543128.accept(Unknown Source)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 707932408 bytes (675 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-config: 0.2.1+build.14
		cotton: 0.6.6+1.14.1-SNAPSHOT
		crochet: 1.0.2
		epicurean: 2.2.0+1.14.1
		fabric: 0.2.7+build.127
		fabric-api-base: 0.1.0+f1618918
		fabric-commands-v0: 0.1.0+f1618918
		fabric-containers-v0: 0.1.0+f1618918
		fabric-content-registries-v0: 0.1.0+f1618918
		fabric-events-interaction-v0: 0.1.0+f1618918
		fabric-item-groups-v0: 0.1.0+f1618918
		fabric-mining-levels-v0: 0.1.0+f1618918
		fabric-networking-v0: 0.1.0+f1618918
		fabric-object-builders-v0: 0.1.0+9232ac87
		fabric-resource-loader-v0: 0.1.0+f1618918
		fabric-tag-extensions-v0: 0.1.0+f1618918
		fabric-tag-hooks: 0.1.0+93af775a
		fabricloader: 0.4.7+build.147
		modmenu: 1.5.4-85
		skillcheck: 1.0.4+1.14.1
	Launched Version: fabric-loader-0.4.7+build.147-1.14.1+build.5
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by Pannoniae** [comment]
The issue seems to be Fabric API, either because methods got deleted, or we didn't update.

**Comment by Juuxel** [comment]
Looks like there's both modular Fabric API (`fabric-X-v0`) and Fabric API 0.2 in that installation; they will conflict.

**Comment by LemmaEOF** [comment]
It looks like it's due to Crochet. I'll PR an update for Raphy to merge in ASAP.

**Comment by LemmaEOF** [comment]
[A pull request has been sent in](https://github.com/raphydaphy/Crochet/pull/1), so I'll close this as soon as the new Crochet is up on CurseForge and I can nest it in.
